// AUTO-GENERATED by scripts/sync-catalog.ts.
// Do not edit by hand — your changes will be overwritten.
// Edit tools/<tool>/*.json via the calibrator instead.

import type { ThemeEntry } from './state';

export const GENERATED_THEME_CATALOG: readonly ThemeEntry[] = [
  {
    id: "default",
    displayName: "Default Room",
    backdropKey: "theme-default-bg",
    musicKey: "theme-default-music",
    rarity: "common",
  },
  {
    id: "cozy",
    displayName: "Cozy Cabin",
    backdropKey: "theme-cozy-bg",
    musicKey: "theme-cozy-music",
    rarity: "uncommon",
  },
  {
    id: "spooky",
    displayName: "Spooky Attic",
    backdropKey: "theme-spooky-bg",
    musicKey: "theme-spooky-music",
    rarity: "rare",
  },
];
