// AUTO-GENERATED by scripts/sync-catalog.ts.
// Do not edit by hand — your changes will be overwritten.
// Edit tools/<tool>/*.json via the calibrator instead.

export const BACKGROUND_CATALOG = {
  default: { id: 'default', displayName: 'Default', backdropKey: 'bg-default', musicKey: 'theme-default-music', rarity: 'common'  as const },
  cozy:    { id: 'cozy',    displayName: 'Cozy',    backdropKey: 'bg-cozy',    musicKey: 'theme-cozy-music',    rarity: 'uncommon' as const },
  spooky:  { id: 'spooky',  displayName: 'Spooky',  backdropKey: 'bg-spooky',  musicKey: 'theme-spooky-music',  rarity: 'rare'     as const },
} as const;

// Legacy alias — keep so existing THEME_CATALOG consumers compile without a rename sweep.
// TODO Phase 5 Task 15: remove this alias once all consumers migrate to BACKGROUND_CATALOG.
export const GENERATED_THEME_CATALOG = [
  BACKGROUND_CATALOG.default,
  BACKGROUND_CATALOG.cozy,
  BACKGROUND_CATALOG.spooky,
] as const;
