"""Generate new cat variants from a base cat shape.

Strategy: cat13 (Butters) is a clean grey shorthair with distinct ear-pink + the
new orange-iris eye fix. Its body fur is a clean 5-shade grey palette. We map
those 5 grey shades to new hues to generate single-tone cats, head/body split
cats, and naturalistic-tabby cats — leaving ears, eyes, and outlines untouched.

Outputs to:
  assets-raw/cat<N>/cat<N>_<anim>_<NN>.png  (one new cat dir per variant)
  tools/cats/cats.json  (appends stub entries with autogenerated names)

Usage:
  python3 scripts/gen-cat-variants.py        # generates the full curated set
  python3 scripts/gen-cat-variants.py --dry  # report what would be made
"""
import colorsys
import json
import shutil
import sys
from pathlib import Path
from PIL import Image
import numpy as np

ROOT = Path('.')
RAW = ROOT / 'assets-raw'
BASE_CAT = 'cat13'  # Butters — clean grey body, eye-fix applied
CATS_JSON = ROOT / 'tools/cats/cats.json'

# Pixel colors that must NEVER be recolored — eyes, ear pink, outline, etc.
# Captured from cat13 after eye-fix. Anything not in BASE_FUR_PALETTE
# is left untouched in the output frames.
BASE_FUR_PALETTE = [
    (125, 136, 150),  # lightest body
    (117, 128, 144),  # light-mid body
    (90, 100, 113),   # mid body
    (74, 83, 96),     # dark body
    (42, 49, 58),     # darkest body shade
]

# Tone-mapping helper — for a base RGB, return its HSL.
def rgb_to_hls(r, g, b):
    return colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)


def hls_to_rgb(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return (int(round(r * 255)), int(round(g * 255)), int(round(b * 255)))


def shift_palette(palette, target_h_deg, target_s, light_bias=0.0):
    """Map each base shade to the new hue, preserving original lightness ordering.
    Saturation set to target_s. light_bias shifts lightness ± (clamped to [0,1])."""
    out = []
    for (r, g, b) in palette:
        h, l, s = rgb_to_hls(r, g, b)
        nl = max(0.0, min(1.0, l + light_bias))
        out.append(hls_to_rgb(target_h_deg / 360.0, nl, target_s))
    return out


def shift_palette_naturalistic(palette, target_h_deg, target_s_base):
    """For subtle/natural cat colors — keep low saturation, just shift hue.
    target_s_base is a multiplier (0..1) on natural fur saturation."""
    out = []
    for (r, g, b) in palette:
        h, l, s = rgb_to_hls(r, g, b)
        # Naturalistic: cap saturation, keep desaturated overall
        new_s = min(target_s_base, s + 0.25)
        out.append(hls_to_rgb(target_h_deg / 360.0, l, new_s))
    return out


# Curated variant catalog.
# Each entry: (name, kind, params)
#   kind='solid'    params=(hue_deg, saturation)
#   kind='split'    params=(head_hue, head_sat, head_light_bias, body_hue, body_sat, body_light_bias)
#                   light_bias shifts lightness ±. 0 = unchanged. Used for
#                   black (-large) vs white (+large) endpoints.
# Note: cat79..cat90 are already shipped (Bright single-tone) — keep them.
# This list is regenerated from cat91 onward.
VARIANTS = [
    # Pastel L/R splits (cat91-94, 96, 99) — kept from prior round
    ('Sherbet',    'split',   (15, 0.55, 0.0, 335, 0.45, 0.0)),   # cat91 peach + pink
    ('Macaron',    'split',   (335, 0.45, 0.0, 200, 0.35, 0.0)),  # cat92 pink + sky blue
    ('Seaglass',   'split',   (170, 0.45, 0.0, 280, 0.40, 0.0)),  # cat93 mint + lavender
    ('Lullaby',    'split',   (280, 0.40, 0.0, 200, 0.35, 0.0)),  # cat94 lavender + sky
    # NEW (cat95) — head/body, black head + white body
    ('Bishop',     'hbsplit', (0, 0.0, -0.65, 0, 0.0, 0.55)),     # cat95 H:black B:white
    ('Cottoncandy','split',   (335, 0.50, 0.0, 200, 0.45, 0.0)),  # cat96 pink + baby blue
    # NEW (cat97) — black head + grey body
    ('Knight',     'hbsplit', (0, 0.0, -0.60, 0, 0.0, -0.20)),    # cat97 H:black B:grey
    # NEW (cat98) — blue head + white body (like image cat38)
    ('Sailor',     'hbsplit', (200, 0.50, 0.0, 0, 0.0, 0.55)),    # cat98 H:blue B:white
    ('Lagoon',     'split',   (175, 0.55, 0.0, 220, 0.55, 0.0)),  # cat99 aqua + soft blue
    # NEW (cat100) — green head + brown body (like image cat41)
    ('Ranger',     'hbsplit', (110, 0.40, 0.0, 25, 0.40, -0.10)), # cat100 H:green B:brown
    # NEW (cat101) — lavender head + blue body (like image cat42)
    ('Wizard',     'hbsplit', (280, 0.40, 0.0, 220, 0.50, 0.0)),  # cat101 H:lavender B:blue
    # NEW (cat102) — red head + white body (like image cat43)
    ('Strawberry', 'hbsplit', (0, 0.65, -0.05, 0, 0.0, 0.55)),    # cat102 H:red B:white

    # Common-cat L/R splits (cat103-110) — kept
    ('Tuxedo',     'split',   (0, 0.0, -0.65, 0, 0.0, 0.55)),     # cat103 black + white L/R
    ('Bandit',     'split',   (0, 0.0, 0.55, 0, 0.0, -0.65)),     # cat104 white + black L/R
    ('Cinnamon',   'split',   (25, 0.55, 0.0, 0, 0.0, 0.50)),     # cat105 orange + white L/R
    ('Pumpkin',    'split',   (0, 0.0, 0.50, 25, 0.55, 0.0)),     # cat106 white + orange L/R
    ('Domino',     'split',   (0, 0.0, -0.55, 25, 0.55, 0.0)),    # cat107 black + orange L/R
    ('Spice',      'split',   (25, 0.55, 0.0, 0, 0.0, -0.55)),    # cat108 orange + black L/R
    ('Storm',      'split',   (0, 0.0, -0.20, 0, 0.0, 0.50)),     # cat109 grey + white L/R
    ('Mittens',    'split',   (0, 0.0, 0.50, 0, 0.0, -0.20)),     # cat110 white + grey L/R
    # NEW (cat111) — orange head + cream body
    ('Apricot',    'hbsplit', (25, 0.55, 0.0, 30, 0.30, 0.20)),   # cat111 H:orange B:cream
    # NEW (cat112) — black head + orange body (like image cat39)
    ('Lava',       'hbsplit', (0, 0.0, -0.60, 25, 0.55, 0.0)),    # cat112 H:black B:orange
    ('Coal',       'split',   (0, 0.0, -0.60, 0, 0.0, -0.25)),    # cat113 full black + grey
    ('Snowdrop',   'split',   (0, 0.0, 0.55, 200, 0.10, 0.0)),    # cat114 white + pale grey
    ('Caramel',    'split',   (25, 0.45, 0.0, 30, 0.25, 0.25)),   # cat115 caramel + cream
    ('Toffee',     'split',   (30, 0.25, 0.25, 25, 0.45, 0.0)),   # cat116 cream + caramel
]


def build_pixel_map(base_palette, target_palette) -> dict:
    return {base: tgt for base, tgt in zip(base_palette, target_palette)}


def recolor_frame_solid(a: np.ndarray, pmap: dict) -> np.ndarray:
    out = a.copy()
    h, w = a.shape[:2]
    # Use vectorized lookup
    r = a[..., 0]
    g = a[..., 1]
    b = a[..., 2]
    alpha = a[..., 3]
    for src, tgt in pmap.items():
        mask = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0)
        out[mask, 0] = tgt[0]
        out[mask, 1] = tgt[1]
        out[mask, 2] = tgt[2]
    return out


SPLIT_X = 50  # fixed canvas column for vertical L/R split. Matches
# cat13_idle_00 silhouette midpoint AND cat.ts CANVAS_HORIZONTAL_CENTER.
# Using a fixed value (not per-frame midpoint) keeps the split line locked
# to the cat's body center across all animation frames — otherwise the
# boundary "walks" as the tail extends or the head bobs (Tim's bug).


def recolor_frame_split(a: np.ndarray, left_map: dict, right_map: dict) -> np.ndarray:
    """Vertical L/R split — apply left_map to the cat's left half, right_map
    to the right half. Split line is FIXED at canvas x=SPLIT_X (50) across
    every frame so the boundary doesn't jitter as the cat animates.
    """
    out = a.copy()
    r = a[..., 0]
    g = a[..., 1]
    b = a[..., 2]
    alpha = a[..., 3]

    xs = np.arange(a.shape[1])[None, :]
    left_mask = xs < SPLIT_X
    right_mask = ~left_mask

    for src, tgt in left_map.items():
        m = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0) & left_mask
        out[m, 0] = tgt[0]
        out[m, 1] = tgt[1]
        out[m, 2] = tgt[2]
    for src, tgt in right_map.items():
        m = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0) & right_mask
        out[m, 0] = tgt[0]
        out[m, 1] = tgt[1]
        out[m, 2] = tgt[2]
    return out


def find_chin_safe_split_y(a: np.ndarray, default: int = 44) -> int:
    """Find the row just below the chin where the body starts widening.

    Scans the head/neck transition zone (y=36..50) for the narrowest row
    (the chin/neck waist), then returns one row below it. The waist is
    where the silhouette is at its thinnest between the head bubble and
    the body bubble. Splitting just below keeps the full chin in the
    head color. Falls back to `default` (=44) when no clear waist is
    found — e.g. sleep/stretch frames where the cat doesn't have the
    standard head-on-top pose.
    """
    alpha = a[..., 3]
    best_y = None
    best_w = 10 ** 9
    for y in range(36, 50):
        opaque = np.where(alpha[y] > 100)[0]
        if len(opaque) < 4:
            continue
        # Use the OUTLINE-to-outline width (max - min), which corresponds
        # to the silhouette's bounding box at this row.
        w = int(opaque.max() - opaque.min() + 1)
        if w < best_w:
            best_w = w
            best_y = y
    if best_y is None:
        return default
    return best_y + 1


def recolor_frame_hbsplit(a: np.ndarray, head_map: dict, body_map: dict) -> np.ndarray:
    """Horizontal HEAD/BODY split — full head (ears, face, CHIN) gets
    head_map, chest/belly/legs/tail gets body_map.

    Split line is computed per-frame via silhouette waist detection so the
    chin always stays head-color (the old fixed split_y=42 sliced through
    the chin underside — that's the explicit bug Tim flagged).
    """
    out = a.copy()
    r = a[..., 0]
    g = a[..., 1]
    b = a[..., 2]
    alpha = a[..., 3]

    split_y = find_chin_safe_split_y(a)
    ys = np.arange(a.shape[0])[:, None]
    head_mask = ys < split_y
    body_mask = ~head_mask

    for src, tgt in head_map.items():
        m = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0) & head_mask
        out[m, 0] = tgt[0]
        out[m, 1] = tgt[1]
        out[m, 2] = tgt[2]
    for src, tgt in body_map.items():
        m = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0) & body_mask
        out[m, 0] = tgt[0]
        out[m, 1] = tgt[1]
        out[m, 2] = tgt[2]
    return out


def find_next_cat_id() -> int:
    existing = [int(p.name[3:]) for p in RAW.iterdir() if p.is_dir() and p.name.startswith('cat') and p.name[3:].isdigit()]
    return max(existing) + 1


def load_cats_json() -> list:
    return json.loads(CATS_JSON.read_text())


def save_cats_json(data: list):
    CATS_JSON.write_text(json.dumps(data, indent=2) + '\n')


def make_one_variant(name: str, kind: str, params, new_id: int, dry: bool = False) -> dict:
    new_cat = f'cat{new_id}'
    src_dir = RAW / BASE_CAT
    dst_dir = RAW / new_cat
    if dry:
        return {'name': name, 'id': new_cat, 'kind': kind, 'params': params}

    dst_dir.mkdir(parents=True, exist_ok=True)
    if kind == 'solid':
        hue, sat = params
        tgt = shift_palette(BASE_FUR_PALETTE, hue, sat)
        pmap = build_pixel_map(BASE_FUR_PALETTE, tgt)
        for fp in sorted(src_dir.glob(f'{BASE_CAT}_*.png')):
            a = np.array(Image.open(fp).convert('RGBA'))
            out = recolor_frame_solid(a, pmap)
            out_name = fp.name.replace(BASE_CAT, new_cat)
            Image.fromarray(out, 'RGBA').save(dst_dir / out_name)

    elif kind == 'split':
        h_hue, h_sat, h_bias, b_hue, b_sat, b_bias = params
        h_tgt = shift_palette(BASE_FUR_PALETTE, h_hue, h_sat, h_bias)
        b_tgt = shift_palette(BASE_FUR_PALETTE, b_hue, b_sat, b_bias)
        l_map = build_pixel_map(BASE_FUR_PALETTE, h_tgt)
        r_map = build_pixel_map(BASE_FUR_PALETTE, b_tgt)
        # Vertical L/R split — left half of cat = h_* color, right half = b_*
        # color. Params keep their head/body names for backwards-compat with
        # the VARIANTS table, but spatially the split runs down the cat's
        # midline (per-frame).
        for fp in sorted(src_dir.glob(f'{BASE_CAT}_*.png')):
            a = np.array(Image.open(fp).convert('RGBA'))
            out = recolor_frame_split(a, l_map, r_map)
            out_name = fp.name.replace(BASE_CAT, new_cat)
            Image.fromarray(out, 'RGBA').save(dst_dir / out_name)

    elif kind == 'hbsplit':
        h_hue, h_sat, h_bias, b_hue, b_sat, b_bias = params
        h_tgt = shift_palette(BASE_FUR_PALETTE, h_hue, h_sat, h_bias)
        b_tgt = shift_palette(BASE_FUR_PALETTE, b_hue, b_sat, b_bias)
        h_map = build_pixel_map(BASE_FUR_PALETTE, h_tgt)
        b_map = build_pixel_map(BASE_FUR_PALETTE, b_tgt)
        # Horizontal HEAD/BODY split: whole head incl chin = h_* color,
        # chest/belly/legs/tail = b_* color. Split y picked per-frame from
        # silhouette waist (chin-safe).
        for fp in sorted(src_dir.glob(f'{BASE_CAT}_*.png')):
            a = np.array(Image.open(fp).convert('RGBA'))
            out = recolor_frame_hbsplit(a, h_map, b_map)
            out_name = fp.name.replace(BASE_CAT, new_cat)
            Image.fromarray(out, 'RGBA').save(dst_dir / out_name)

    elif kind == 'natural':
        hue, sat = params
        tgt = shift_palette_naturalistic(BASE_FUR_PALETTE, hue, sat)
        pmap = build_pixel_map(BASE_FUR_PALETTE, tgt)
        for fp in sorted(src_dir.glob(f'{BASE_CAT}_*.png')):
            a = np.array(Image.open(fp).convert('RGBA'))
            out = recolor_frame_solid(a, pmap)
            out_name = fp.name.replace(BASE_CAT, new_cat)
            Image.fromarray(out, 'RGBA').save(dst_dir / out_name)
    else:
        raise ValueError(f'unknown kind: {kind}')

    return {'name': name, 'id': new_cat, 'kind': kind, 'params': params}


def main():
    dry = '--dry' in sys.argv

    next_id = find_next_cat_id()
    print(f'Next available cat ID: cat{next_id}')
    print(f'Base cat: {BASE_CAT}')
    print(f'Variants to generate: {len(VARIANTS)}\n')

    cats_data = load_cats_json()
    existing_ids = {c['id'] for c in cats_data}
    print(f'Current cats.json entries: {len(cats_data)}')

    results = []
    cur_id = next_id
    for name, kind, params in VARIANTS:
        r = make_one_variant(name, kind, params, cur_id, dry=dry)
        results.append(r)
        print(f'  cat{cur_id:3d}  {name:12s}  {kind:8s}  {params}')
        cur_id += 1

    # Append to cats.json
    if not dry:
        for r in results:
            if r['id'] in existing_ids:
                continue
            cats_data.append({
                'id': r['id'],
                'name': r['name'],
                'rarity': 'common',
            })
        save_cats_json(cats_data)
        print(f'\ncats.json updated. New total: {len(cats_data)} entries.')

    print(f'\nGenerated {len(results)} variants. Highest new cat: cat{cur_id - 1}')


if __name__ == '__main__':
    main()
